### ISSUE TITLE
Aplicación bloqueada al levantarla

### ISSUE THREAD

**Issue by Tahuri** [centaurialpha/edis#25]
La aplicación se queda bloqueada cuando intenta abrir un proyecto inexistente, dicho de otra forma, si se crea un proyecto o se abre un archivo .c y luego se cierra edis, se elimina el proyecto o .c y luego se abre edis, este queda bloqueado intentando abrir el archivo, y no me deja acceder a la ventana de error para darle aceptar y continuar con la ejecución del ide.

El cartel del error queda detras de la ventana que dice cargando y esta ventana con la leyenda de cargando no se puede mover y por ende no puedo darle a aceptar.

Estoy usando SO Archlinux con gnome 3

"sni-qt/3939" WARN  11:09:11.736 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE 
ERROR:src.ui.containers.editor_container:Error opening file: [Errno 2] No existe el fichero o el directorio: '/home/tahuri/Documentos/ProyectoEdis/PruebasEdis/main.c'

**Comment by centaurialpha** [comment]
Solucionado!
